
const Map<String, String> ar = {
  'appTitle': 'أدوات الصحة',
  'bmiCalculator': 'حاسبة مؤشر كتلة الجسم',
  'bmiSubtitle': 'احسب وزنك المثالي بسهولة',
  'bmrCalculator': 'معدل الأيض الأساسي',
  'bmrSubtitle': 'اكتشف احتياجاتك اليومية من السعرات',
  'bodyFatCalculator': 'حاسبة نسبة الدهون',
  'bodyFatSubtitle': 'تابع تركيب جسمك بسلاسة',
  'advancedBmiCalculator': 'حاسبة متقدمة لمؤشر كتلة الجسم',
  'bmrCalculatorTitle': 'حاسبة معدل الأيض',
  'bodyFatCalculatorTitle': 'حاسبة نسبة الدهون',
  'pleaseCorrectErrors': 'يرجى تصحيح الأخطاء',
  'pleaseEnterAllNumbers': 'يرجى إدخال جميع الأرقام المطلوبة!',
  'calculationError': 'خطأ في الحساب',
  'errorInCalculation': 'حدث خطأ في الحساب',
  'underweight': 'نقص في الوزن',
  'normalWeight': 'وزن طبيعي',
  'overweight': 'زيادة في الوزن',
  'obese': 'سمنة',
  'gender': 'الجنس',
  'male': 'ذكر',
  'female': 'أنثى',
  'age': 'العمر',
  'years': 'سنوات',
  'enterAge': 'أدخل العمر',
  'weight': 'الوزن',
  'kg': 'كجم',
  'enterWeight': 'أدخل الوزن',
  'height': 'الطول',
  'cm': 'سم',
  'enterHeight': 'أدخل الطول',
  'calculateBmi': 'احسب مؤشر كتلة الجسم',
  'yourBodyAnalysis': 'تحليل جسمك',
  'errorAge': 'يجب أن يكون العمر بين 1-120 سنة',
  'errorWeight': 'يجب أن يكون الوزن بين 20-300 كجم',
  'errorHeight': 'يجب أن يكون الطول بين 50-250 سم',
  'bodyFat': 'نسبة الدهون',
  'percent': '%',
  'enterBodyFat': 'أدخل نسبة الدهون',
  'muscleMass': 'كتلة العضلات',
  'enterMuscleMass': 'أدخل كتلة العضلات',
  'errorBodyFat': 'يجب أن تكون نسبة الدهون بين 2-60%',
  'errorMuscleMass': 'يجب أن تكون كتلة العضلات بين 20-60%',
  'bodyCompositionAnalysis': 'تحليل تركيب الجسم',
  'bodyCompositionSubtitle': 'احصل على تحليل مفصل بنسبة الدهون والكتلة العضلية',
  'bmiScale': 'مقياس مؤشر كتلة الجسم',
  'calculateBmr': 'احسب معدل الأيض',
  'calculateBodyFat': 'احسب نسبة الدهون',
  'waist': 'الخصر',
  'neck': 'الرقبة',
  'hip': 'الأرداف',
  'enterWaist': 'أدخل محيط الخصر',
  'enterNeck': 'أدخل محيط الرقبة',
  'enterHip': 'أدخل محيط الأرداف',
  'errorWaist': 'يجب أن يكون محيط الخصر بين 50-200 سم وأكبر من الرقبة',
  'errorNeck': 'يجب أن يكون محيط الرقبة بين 20-60 سم وأصغر من الخصر',
  'errorHip': 'يجب أن يكون محيط الأرداف بين 60-200 سم',
  'bmiScaleUnderweight': 'نقص الوزن',
  'bmiScaleNormal': 'طبيعي',
  'bmiScaleOverweight': 'زيادة الوزن',
  'bmiScaleObese': 'سمنة',
  'weightGainRequired': 'تحتاج إلى اكتساب {{weight}} كجم للوصول إلى الوزن الطبيعي',
  'weightLossRequired': 'تحتاج إلى فقدان {{weight}} كجم للوصول إلى الوزن الطبيعي',
  'idealWeightRange': 'نطاق الوزن المثالي لطولك',
  'bodyFatPercentage': 'نسبة الدهون في الجسم',
  'muscleMassPercentage': 'نسبة الكتلة العضلية',
  'optional': 'اختياري',
  'addBodyComposition': 'إضافة بيانات تركيب الجسم',
  'calculated': 'تم الحساب',
  'hospitalsTitle': 'المستشفيات',
  'healthTools': 'أدوات الصحة',
  // 'yourBodyAnalysis': 'تحليل جسمك',

  'sedentary': 'قليل الحركة',
  'sedentaryDesc': 'قليل التمرين أو بدون تمرين',
  'lightlyActive': 'نشط قليلاً',
  'lightlyActiveDesc': 'تمرين خفيف 1-3 أيام/أسبوع',
  'moderatelyActive': 'نشط بشكل معتدل',
  'moderatelyActiveDesc': 'تمرين متوسط 3-5 أيام/أسبوع',
  'veryActive': 'نشط جداً',
  'veryActiveDesc': 'تمرين شاق 6-7 أيام/أسبوع',
  'extraActive': 'نشط بشكل استثنائي',
  'extraActiveDesc': 'تمرين شاق جداً وعمل بدني',
  'dailyCalorieNeeds': 'الاحتياجات اليومية من السعرات',
  'calories': 'سعرة حرارية',
  'essentialFat': 'الدهون الأساسية',
  'athletic': 'رياضي',
  'fitness': 'لياقة',
  'average': 'متوسط',
  'needToGain': 'تحتاج إلى اكتساب',
  'needToLose': 'تحتاج إلى فقدان',
  'kgToReachNormal': 'كجم للوصول إلى الوزن الطبيعي',
  'greatBmiInRange': 'ممتاز! مؤشر كتلة جسمك في النطاق الصحي. حافظ على وزنك الحالي.',
  'bmrDescription': 'معدل الأيض الأساسي (BMR) هو عدد السعرات الحرارية التي يحتاجها جسمك في حالة الراحة للحفاظ على الوظائف الفسيولوجية الأساسية.',
  'bodyFatDescription': 'تمثل نسبة الدهون في الجسم كتلة الدهون في جسمك مقارنة بوزن جسمك الكلي.',
  'yourBmiResult': 'نتيجة مؤشر كتلة الجسم',
  'yourBmrResult': 'نتيجة معدل الأيض الأساسي',
  'yourBodyFatResult': 'نتيجة نسبة الدهون في الجسم',
  'invalidValue': 'قيمة غير صالحة',
  'status': 'الحالة',
  'bmi': 'مؤشر كتلة الجسم',
  'pleaseSelectGender':'يرجى تحديد الجنس',


  'login': 'تسجيل الدخول',
  'governmentId': 'الهوية الوطنية',
  'password': 'كلمة المرور',
  'rememberMe': 'تذكرني',
  'forgotPassword': 'نسيت كلمة المرور؟',
  'dontHaveAccount': 'ليس لديك حساب؟',
  'register': 'إنشاء حساب',
  'openNewFile': 'فتح ملف طبي جديد',
  'createAccount': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'confirmPassword': 'تأكيد كلمة المرور',
  'alreadyHaveAccount': 'لديك حساب بالفعل؟',
  'resetPassword': 'إعادة تعيين كلمة المرور',
  'newPassword': 'كلمة المرور الجديدة',
  'medicalServices': 'الخدمات الطبية',
  'mouwasat': 'المواساة',
  'nationality': 'الجنسية',
  'saudi': 'سعودي',
  'nonSaudi': 'غير سعودي',
  'selectHospital': 'اختر المستشفى',
  'birthDate': 'تاريخ الميلاد',
  'maritalStatus': 'الحالة الاجتماعية',
  'religion': 'الديانة',
  'createMedicalFile': 'إنشاء ملف طبي',
  'home': 'الرئيسية',
  'services': 'الخدمات',
  'appointments': 'المواعيد',
  'profile': 'الملف الشخصي',
  'logout': 'تسجيل الخروج',
  'fullName': 'الاسم الكامل',
  'phoneNumber': 'رقم الهاتف',
  'phoneNumberOptional': 'رقم الهاتف (اختياري)',
  'passwordRequirements': 'متطلبات كلمة المرور',
  'atLeast8Characters': '8 أحرف على الأقل',
  'oneUppercaseLetter': 'حرف كبير واحد (A-Z)',
  'oneLowercaseLetter': 'حرف صغير واحد (a-z)',
  'oneNumber': 'رقم واحد (0-9)',
  'oneSpecialCharacter': 'رمز خاص واحد (!@#\$%^&*)',
  'enterFullName': 'أدخل الاسم الكامل',
  'enterPhoneNumber': 'أدخل رقم الهاتف',
  'createPassword': 'إنشاء كلمة مرور',
  'confirmYourPassword': 'تأكيد كلمة المرور',
  'pleaseEnterFullName': 'الرجاء إدخال الاسم الكامل',
  'pleaseEnterPhoneNumber': 'الرجاء إدخال رقم الهاتف',
  'pleaseEnterPassword': 'الرجاء إدخال كلمة المرور',
  'pleaseConfirmPassword': 'الرجاء تأكيد كلمة المرور',
  'passwordsDoNotMatch': 'كلمات المرور غير متطابقة',
  'pleaseMeetAllPasswordRequirements': 'الرجاء تلبية جميع متطلبات كلمة المرور',
  'enterYourGovernmentID': 'أدخل هويتك الوطنية',
  'enterYourPassword': 'أدخل كلمة المرور',
  'enterYourEmail': 'أدخل بريدك الإلكتروني',
  'pleaseEnterValidEmail': 'الرجاء إدخال بريد إلكتروني صالح',
  'pleaseSelectNationality': 'الرجاء اختيار الجنسية',
  'pleaseSelectHospital': 'الرجاء اختيار المستشفى',
  'pleaseSelectBirthDate': 'الرجاء اختيار تاريخ الميلاد',
  'pleaseSelectMaritalStatus': 'الرجاء اختيار الحالة الاجتماعية',
  'pleaseSelectReligion': 'الرجاء اختيار الديانة',
  'governmentIdMustBe10Digits': 'يجب أن يكون رقم الهوية 10 أرقام',
  'passwordMustBeAtLeast8Characters': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
  'passwordResetSuccessful': 'تم إعادة تعيين كلمة المرور بنجاح',
  'passwordResetDescription': 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
  'selectDate': 'اختر التاريخ',
  'gregorian': 'ميلادي',
  'hijri': 'هجري',
  'dateType': 'نوع التاريخ',

// New translations for NewFileScreen
  'createMedicalFileDescription': 'أنشئ ملفك الطبي مع مستشفى المواساة',
  'pleaseEnterGovernmentId': 'الرجاء إدخال رقم الهوية',
  'mustBe10Digits': 'يجب أن يكون 10 أرقام',
  'pleaseEnterEmail': 'الرجاء إدخال البريد الإلكتروني',
  'enterGovernmentId': 'أدخل رقم الهوية',
  'selectBirthDate': 'اختر تاريخ الميلاد',

// Hospitals
  'mouwasatHospitalRiyadh': 'مستشفى المواساة الرياض',
  'mouwasatHospitalDammam': 'مستشفى المواساة الدمام',
  'mouwasatHospitalKhobar': 'مستشفى المواساة الخبر',
  'mouwasatHospitalMedina': 'مستشفى المواساة المدينة',
  'mouwasatHospitalQatif': 'مستشفى المواساة القطيف',

// Marital Statuses
  'single': 'أعزب',
  'married': 'متزوج',
  'divorced': 'مطلق',
  'widowed': 'أرمل',
  'muslim': 'مسلم',
  'christian': 'مسيحي',
  'jewish': 'يهودي',
  'hindu': 'هندوسي',
  'buddhist': 'بوذي',
  'other': 'أخرى',
  'mouwasatHospital': 'مستشفى المواساة',
  'yourHealthOurPriority': 'صحّتك هي أولويتنا',
  "invalidGovernmentId": "رقم الهوية غير صالح",
  "nameMustBeAtLeast2Characters": "يجب أن يكون الاسم على الأقل حرفين",
  "enterPassword": "أدخل كلمة المرور",
  "retry": "إعادة المحاولة",
  "loading": "جاري التحميل..."
};