const Map<String, String> en = {
  'appTitle': 'Health Tools',
  'bmiCalculator': 'Body Mass Index (BMI) Calculator',
  'bmiSubtitle': 'Calculate Your Ideal Weight Easily',
  'bmrCalculator': 'BMR (Basal Metabolic Rate)',
  'bmrSubtitle': 'Discover Your Daily Calorie Needs Effortlessly',
  'bodyFatCalculator': 'Body Fat Calculator',
  'bodyFatSubtitle': 'Track Your Body Composition Seamlessly',
  'advancedBmiCalculator': 'Advanced BMI Calculator',
  'bmrCalculatorTitle': 'BMR Calculator',
  'bodyFatCalculatorTitle': 'Body Fat Calculator',
  'pleaseCorrectErrors': 'Please correct errors',
  'pleaseEnterAllNumbers': 'Please enter all required numbers!',
  'calculationError': 'Calculation error',
  'errorInCalculation': 'Error in calculation',
  'underweight': 'Underweight',
  'normalWeight': 'Normal weight',
  'overweight': 'Overweight',
  'obese': 'Obese',
  'gender': 'Gender',
  'male': 'Male',
  'female': 'Female',
  'age': 'Age',
  'years': 'years',
  'enterAge': 'Enter age',
  'weight': 'Weight',
  'kg': 'kg',
  'enterWeight': 'Enter weight',
  'height': 'Height',
  'cm': 'cm',
  'enterHeight': 'Enter height',
  'calculateBmi': 'Calculate BMI',
  'yourBodyAnalysis': 'Your Body Analysis',
  'errorAge': 'Age must be between 1-120 years',
  'errorWeight': 'Weight must be between 20-300 kg',
  'errorHeight': 'Height must be between 50-250 cm',
  'bodyFat': 'Body Fat',
  'percent': '%',
  'enterBodyFat': 'Enter body fat',
  'muscleMass': 'Muscle Mass',
  'enterMuscleMass': 'Enter muscle mass',
  'errorBodyFat': 'Body fat must be between 2-60%',
  'errorMuscleMass': 'Muscle mass must be between 20-60%',
  'bodyCompositionAnalysis': 'Body Composition Analysis',
  'bodyCompositionSubtitle': 'Get detailed analysis with body fat and muscle mass',
  'bmiScale': 'BMI Scale',
  'calculateBmr': 'Calculate BMR',
  'calculateBodyFat': 'Calculate Body Fat',
  'waist': 'Waist',
  'neck': 'Neck',
  'hip': 'Hip',
  'enterWaist': 'Enter waist circumference',
  'enterNeck': 'Enter neck circumference',
  'enterHip': 'Enter hip circumference',
  'errorWaist': 'Waist must be between 50-200 cm and larger than neck',
  'errorNeck': 'Neck must be between 20-60 cm and smaller than waist',
  'errorHip': 'Hip must be between 60-200 cm',
  'bmiScaleUnderweight': 'Underweight',
  'bmiScaleNormal': 'Normal',
  'bmiScaleOverweight': 'Overweight',
  'bmiScaleObese': 'Obese',
  'weightGainRequired': 'You need to gain {{weight}} kg to reach normal weight',
  'weightLossRequired': 'You need to lose {{weight}} kg to reach normal weight',
  'idealWeightRange': 'Ideal weight range for your height',
  'bodyFatPercentage': 'Body Fat Percentage',
  'muscleMassPercentage': 'Muscle Mass Percentage',
  'optional': 'Optional',
  'addBodyComposition': 'Add Body Composition Data',
  'calculated': 'Calculated',
  'hospitalsTitle': 'Hospitals',
  'healthTools': 'Health Tools',
  // 'yourBodyAnalysis': 'Your Body Analysis',



  'sedentary': 'Sedentary',
  'sedentaryDesc': 'Little or no exercise',
  'lightlyActive': 'Lightly Active',
  'lightlyActiveDesc': 'Light exercise 1-3 days/week',
  'moderatelyActive': 'Moderately Active',
  'moderatelyActiveDesc': 'Moderate exercise 3-5 days/week',
  'veryActive': 'Very Active',
  'veryActiveDesc': 'Hard exercise 6-7 days/week',
  'extraActive': 'Extra Active',
  'extraActiveDesc': 'Very hard exercise & physical job',
  'dailyCalorieNeeds': 'Daily Calorie Needs',
  'calories': 'calories',
  'essentialFat': 'Essential Fat',
  'athletic': 'Athletic',
  'fitness': 'Fitness',
  'average': 'Average',
  'needToGain': 'You need to gain',
  'needToLose': 'You need to lose',
  'kgToReachNormal': 'kg to reach normal weight',
  'greatBmiInRange': 'Great! Your BMI is in the healthy range. Maintain your current weight.',
  'bmrDescription': 'Your Basal Metabolic Rate (BMR) is the number of calories your body needs at rest to maintain basic physiological functions.',
  'bodyFatDescription': 'Body fat percentage represents the amount of fat mass in your body compared to your total body weight.',
  'yourBmiResult': 'Your BMI Result',
  'yourBmrResult': 'Your BMR Result',
  'yourBodyFatResult': 'Your Body Fat Result',
  'invalidValue': 'Invalid value',
  'status': 'Status',
  'bmi': 'BMI',
  'pleaseSelectGender' : 'Please Select Gender',



  'login': 'Login',
  'governmentId': 'Government ID',
  'password': 'Password',
  'rememberMe': 'Remember me',
  'forgotPassword': 'Forgot Password?',
  'dontHaveAccount': "Don't have an account?",
  'register': 'Register',
  'openNewFile': 'Open New Medical File',
  'createAccount': 'Create Account',
  'email': 'Email',
  'confirmPassword': 'Confirm Password',
  'alreadyHaveAccount': 'Already have an account?',
  'resetPassword': 'Reset Password',
  'newPassword': 'New Password',
  'medicalServices': 'Medical Services',
  'mouwasat': 'Mouwasat',
  'nationality': 'Nationality',
  'saudi': 'Saudi',
  'nonSaudi': 'Non-Saudi',
  'selectHospital': 'Select Hospital',
  'birthDate': 'Birth Date',
  'maritalStatus': 'Marital Status',
  'religion': 'Religion',
  'createMedicalFile': 'Create Medical File',
  'home': 'Home',
  'services': 'Services',
  'appointments': 'Appointments',
  'profile': 'Profile',
  'logout': 'Logout',
  'fullName': 'Full Name',
  'phoneNumber': 'Phone Number',
  'phoneNumberOptional': 'Phone Number (Optional)',
  'passwordRequirements': 'Password Requirements',
  'atLeast8Characters': 'At least 8 characters',
  'oneUppercaseLetter': 'One uppercase letter (A-Z)',
  'oneLowercaseLetter': 'One lowercase letter (a-z)',
  'oneNumber': 'One number (0-9)',
  'oneSpecialCharacter': 'One special character (!@#\$%^&*)',
  'enterFullName': 'Enter full name',
  'enterPhoneNumber': 'Enter phone number',
  'createPassword': 'Create a password',
  'confirmYourPassword': 'Confirm your password',
  'pleaseEnterFullName': 'Please enter full name',
  'pleaseEnterPhoneNumber': 'Please enter phone number',
  'pleaseEnterPassword': 'Please enter password',
  'pleaseConfirmPassword': 'Please confirm password',
  'passwordsDoNotMatch': 'Passwords do not match',
  'pleaseMeetAllPasswordRequirements': 'Please meet all password requirements',
  'enterYourGovernmentID': 'Enter your Government ID',
  'enterYourPassword': 'Enter your password',
  'enterYourEmail': 'Enter your email',
  'pleaseEnterValidEmail': 'Please enter a valid email',
  'pleaseSelectNationality': 'Please select nationality',
  'pleaseSelectHospital': 'Please select hospital',
  'pleaseSelectBirthDate': 'Please select birth date',
  'pleaseSelectMaritalStatus': 'Please select marital status',
  'pleaseSelectReligion': 'Please select religion',

  // New translations for NewFileScreen
  'createMedicalFileDescription': 'Create your medical file with Mouwasat Hospital',
  'pleaseEnterGovernmentId': 'Please enter Government ID',
  'mustBe10Digits': 'must be 10 digits',
  'pleaseEnterEmail': 'Please enter email',
  'enterGovernmentId': 'Enter Government ID',
  'selectBirthDate': 'Select birth date',

  // Hospitals
  'mouwasatHospitalRiyadh': 'Mouwasat Hospital Riyadh',
  'mouwasatHospitalDammam': 'Mouwasat Hospital Dammam',
  'mouwasatHospitalKhobar': 'Mouwasat Hospital Khobar',
  'mouwasatHospitalMedina': 'Mouwasat Hospital Medina',
  'mouwasatHospitalQatif': 'Mouwasat Hospital Qatif',

  // Marital Statuses
  'single': 'Single',
  'married': 'Married',
  'divorced': 'Divorced',
  'widowed': 'Widowed',

  // Religions
  'muslim': 'MUSLIM',
  'christian': 'CHRISTIAN',
  'jewish': 'JEWISH',
  'hindu': 'HINDU',
  'buddhist': 'BUDDHIST',
  'other': 'OTHER',
  'governmentIdMustBe10Digits': 'Government ID must be 10 digits',
  'passwordMustBeAtLeast8Characters': 'Password must be at least 8 characters',
  'passwordResetSuccessful': 'Password Reset Successful',
  'passwordResetDescription': 'Your password has been reset successfully. You can now login with your new password.',
  'selectDate': 'Select Date',
  'gregorian': 'Gregorian',
  'hijri': 'Hijri',
  'dateType': 'Date Type',
  'mouwasatHospital': 'Mouwasat Hospital',
  'yourHealthOurPriority': 'Your Health, Our Priority',
  "invalidGovernmentId": "invalid Government Id",
  "nameMustBeAtLeast2Characters": "name Must Be AtLeast 2 Characters",
  "enterPassword": "enter Password",
  "retry": "retry",
  "loading": "loading"



};
